### ISSUE TITLE
Need to cut a new release to include the `noAuthDialog`

### ISSUE THREAD

**Issue by bmcminn** [Mozu/grunt-mozu-appdev-sync#2]
https://www.npmjs.com/package/grunt-mozu-appdev-sync

NPM currently lists `2.2.0` as the current version of this repository which I verified does not have the latest fix for the `options.noAuthDialog` on Windows I discussed with @zetlen in https://github.com/zetlen/clortho/issues/1

**Comment by bencripps** [comment]
Released
